excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - R.generated.swift
  - .build # Where Swift Package Manager checks out dependency sources

# Rules to manually opt-in to
opt_in_rules:
    - anonymous_argument_in_multiline_closure
    - array_init
    - async_without_await
    - attributes
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - direct_return
    - discouraged_assert
    - discouraged_none_name
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - explicit_init
    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    - file_name
    - file_name_no_space
    - file_types_order
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - function_default_parameter_at_end
    - identical_operands
    - implicit_return
    - implicitly_unwrapped_optional
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
#    - missing_docs
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - nimble_operator
    - no_empty_block
    - no_extension_access_modifier
    - no_grouping_extension
    - number_separator
    - operator_usage_whitespace
    - optional_enum_case_matching
    - override_in_extension
    - pattern_matching_keywords
    - period_spacing
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - private_subject
    - private_swiftui_state
    - reduce_into
    - redundant_nil_coalescing
    - redundant_self_in_closure
    - redundant_type_annotation
    - required_enum_case
    - return_value_from_void_function
    - shorthand_argument
    - shorthand_optional_binding
    - sorted_enum_cases
    - sorted_first_last
    - sorted_imports
    - static_operator
    - strict_fileprivate
    - switch_case_on_newline
    - toggle_bool
    - trailing_closure
    - type_contents_order
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - unused_parameter
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

# Add any default rules you wish to disable here
disabled_rules:

# These all seem quite helpful
analyzer_rules:
    - capture_variable
    - explicit_self
    - typesafe_array_init
    - unused_declaration
    - unused_import

# Too many line breaks can make code harder to read
line_length:
    warning: 200
    error: 220

# CLI tools have a lot in the run function... Do not always disable
function_body_length:
    warning: 75
    error: 100
