#################################################################################################################################
# release.yml
# Created on 03/27/2025
#
# Copyright (C) 2025 Mehmet Bertan Tarakcioglu, Under the MIT License
#
# This file was originally created as part of the WatchDuck project.
#
# WatchDuck is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# WatchDuck is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with WatchDuck.
# If not, see <https://www.gnu.org/licenses/>.
#################################################################################################################################

# Part of the CI/CD pipeline for WatchDuck.
# This workflow is used to create a new release of WatchDuck with a new version tag input.

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "New release tag to create (e.g. 0.4.2)"
      run_swiftlint:
        type: boolean
        required: true
        default: true
        description: "Run SwiftLint before building. Overridden if repo variable is false."
      update_changelog:
        type: boolean
        required: true
        default: true
        description: "Auto-prepare release notes and update the changelog. Overridden if repo variable is false."

jobs:
  call-release:
    uses: BertanT/Swift-Executable-CI/.github/workflows/release.yml@5576c29badd4468c399b07cac5629b102d8a25ff
    with:
      version: ${{ inputs.version }}
      exec_name: ${{ vars.EXEC_NAME }}
      swift_toolchain_version: ${{ vars.SWIFT_TOOLCHAIN_VERSION }}
      linux_sdk_url: ${{ vars.LINUX_SDK_URL }}
      linux_sdk_checksum: ${{ vars.LINUX_SDK_CHECKSUM }}
      run_swiftlint: ${{ vars.RELEASE_RUN_SWIFTLINT != 'false' && (github.event_name != 'workflow_dispatch' || inputs.run_swiftlint) }}
      update_changelog: ${{ vars.UPDATE_CHANGELOG != 'false' && (github.event_name != 'workflow_dispatch' || inputs.update_changelog) }}
